### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by antoinepairet**

### CODE REVIEW

**Comment by nicolas-b12** [comment]
@antoinepairet Can we merge this as we use the withUser methods ?

**Comment by cebamps** [comment]
There seems to be a problem with this PR. M
I will check it when I arrive at the office.

**Comment by cebamps** [comment]
Not sure why the contact and patient x-api methods that throw errors are in conflict... The conflicts should be resolved by keeping the methods that return `never` and throw an error.

**Comment by antoinepairet** [comment]
@phil1618 Can you solve the conflicts so we can merge? 
Thanks

**Comment by phil1618** [comment]
@antoinepairet On it

**Pull request merged**
